version: 2.1

orbs:
  python: circleci/python@1.4.0
  codecov: codecov/codecov@3.2.0

jobs:
  test-and-coverage:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: ""
          args: coverage
      - run:
          name: Run tests and collect coverage
          command: |
            coverage run -m unittest -v
            coverage xml
      - codecov/upload

workflows:
  main:
    jobs:
      - test-and-coverage
